### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by YanfaAdiPutra** [jhlau/doc2vec#16]
I try to run your train_model.py with my pretrained word2vec model and acquried this error then i try to use pretrained word2vec AP news skip-gram and english wiki but this error keep coming 
Is there anymore step i need to run this train_model.py?

ps: i already use your forked gensim too

**Comment by vikaschib7** [comment]
use encoding='utf-8'
