### ISSUE TITLE
error while loading model

### ISSUE THREAD

**Issue by Pked01** [jhlau/doc2vec#17]
I am using python3
also i tried loading with .tgz file directly...please help
![image](https://user-images.githubusercontent.com/8408124/36635505-249d98ac-19dc-11e8-8c8c-0ec87a94b409.png)

**Comment by jhlau** [comment]
Python3 isn't officially supported.

**Comment by Pked01** [comment]
https://github.com/jhlau/gensim
i have used forked version of gensim(what you have shared),
testing has been done on python3 as per readme

**Comment by jhlau** [comment]
There are issues loading python2 pickle files, see here: https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

**Comment by ShrikanthSingh** [comment]
But for me it loads perfectly on google colab. And I checked the version of python as it shows 3.6. Will i face any issue in the future.
