### ISSUE TITLE
Doc2vec Attribute error while loading

### ISSUE THREAD

**Issue by Senhaji-Rhazi-Hamza** [jhlau/doc2vec#19]
1st thanks for shairing your pretrained vector.

i downloaded the pre-trained doc2vec

i run this peice of code 
```
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
model = Doc2Vec.load("doc2vec.bin ")
```
i get this error
AttributeError: 'Doc2Vec' object has no attribute 'batch_words'

while doc2vec.bin   doc2vec.bin.syn0.npy  doc2vec.bin.syn1neg.npy
are in the same folder at the root

**Comment by jhlau** [comment]
Are you using my forked gensim code: https://github.com/jhlau/gensim

**Comment by jhlau** [comment]
You have to use the forked version, because it's modified to take in pre-trained embeddings.

**Comment by Senhaji-Rhazi-Hamza** [comment]
Thank you !!
