### ISSUE TITLE
AttributeError: 'Doc2Vec' object has no attribute 'neg_labels'

### ISSUE THREAD

**Issue by masa-nudt** [jhlau/doc2vec#22]
While I'm loading your pre-trained DOC2VEC models, aka. English Wikipedia DBOW (1.4GB) and Associated Press News DBOW (0.6GB) , error AttributeError: 'Doc2Vec' object has no attribute 'neg_labels' occurs.

I also notice that in the loaded model, negative is set to 5 but no neg_labels are provided.

**Comment by jhlau** [comment]
You'll need to use my forked version of gensim: https://github.com/jhlau/gensim

**Comment by masa-nudt** [comment]
Yes, I'am using your forked version.
I noticed that there are three bin files within each model.
I assume that I should load all of them, but how can I achieve this?

Thanks for your patience, I sorry to disturb you again.

**Comment by rbarriaa** [comment]
Hi

I am facing the same problem.

I am using the forked version at https://github.com/jhlau/gensim,
but still after loading model="doc2vec.bin" from the AP News,
I get an error "Doc2Vec object has no attribute 'neg_labels'".

Any ideas how to solve this?

Kind Regards,
Rodrigo

**Comment by mmunsi2** [comment]
Hello, I'm facing the same issue.

**Comment by Abhimanyu100** [comment]
I'm too facing this same issue.

**Comment by rbarriaa** [comment]
Hi,

After several tries, I ended up using an older version, that didnt have
that problem

**Comment by Abhimanyu100** [comment]
Hey, @rbarriaa  Which library version you are talking about?

**Comment by parshin76** [comment]
I'm also facing the same issue. @rbarriaa Can you please explain more what is this older version?
