### ISSUE TITLE
worker_count == No of Cores in we want to use ? in this line https://github.com/jhlau/doc2vec/blob/158df84b83c1b2b3038c420df03a3f063f7a50be/train_model.py#L14

### ISSUE THREAD

**Issue by amitjslearn** [jhlau/doc2vec#32]
https://github.com/jhlau/doc2vec/blob/158df84b83c1b2b3038c420df03a3f063f7a50be/train_model.py#L14
What does the variable worker_count mean? Does it imply the number of cores we want to use?
When worker_count = -1, does it mean, use all cores/processes (will it be applicable here)?

**Comment by jhlau** [comment]
Yeap.
