### ISSUE TITLE
vector_size = 300 : Can I increase the vector size while using the Associated Press News DBOW (0.6GB)

### ISSUE THREAD

**Issue by amitjslearn** [jhlau/doc2vec#33]
https://github.com/jhlau/doc2vec/blob/158df84b83c1b2b3038c420df03a3f063f7a50be/train_model.py#L7
In the above line can I increase the vector_size while fine-tuning it with [Associated Press News DBOW (0.6GB)](https://ibm.ent.box.com/s/9ebs3c759qqo1d8i7ed323i6shv2js7e).

**Comment by jhlau** [comment]
No. You'd have to train from scratch.

**Comment by amitjslearn** [comment]
> No. You'd have to train from scratch.

But, I am able to train it, completed 50% till now, still its training

**Comment by ShrikanthSingh** [comment]
> > No. You'd have to train from scratch.
> 
> But, I am able to train it, completed 50% till now, still its training

Did you train using the same "toy_data/train_docs.txt" given in the repository ?

**Comment by amitjslearn** [comment]
No, I had my own dataset.
