### ISSUE TITLE
Forked version of gensim

### ISSUE THREAD

**Issue by chaitjo** [jhlau/doc2vec#4]
I understand that in order to use pretrained word embeddings to train the doc2vec models, we should install your forked version of gensim. However, I have failed to configure it properly with a C compiler. (MINGW in my case, could be BLAS etc.) I'm on windows and am using Anaconda.

I tried installing straight from setup.py, using pip, and even created a conda package and installed using that. Each time, I did succeed in installing the forked version of gensim.

However, every time I tried the following commands in a python shell-
```
>>> import gensim
>>> gensim.models.word2vec.FAST_VERSION
```
...the output was a -1. This meant that training would be very, very slow. (70 times slower iirc.)

How do I get your version and still retain the link to the C compiler? 
(If I install the current distributed version using `conda install gensim`, it is linked to my MINGW.)

**Comment by jhlau** [comment]
Hi, this isn't a forked version issue. Please post it on the canonical gensim forum.

**Comment by chaitjo** [comment]
My apologies for posting here. I solved the issue by editing all the files you changed. I modified `word2vec.py` and `doc2vec.py` according to the forked version's commit history and it seems to be working perfectly well right now.

**Comment by drussellmrichie** [comment]
Having the same issue. @chaitjo I realize you did this 1.5 years ago, but do you remember more specifically what you did? I do have a c compiler that my master version of gensim is able to see. Seems it's just a matter of getting this forked version of gensim to see it...?

**Comment by chaitjo** [comment]
Hey @drussellmrichie. I'm obviously not 100% sure about this, but here's what I think I did 1.5 years ago:
1. Installed gensim normally (not @jhlau's fork)
2. Manually edited the two files in the package by copying the changes made here: https://github.com/jhlau/gensim/commits/develop 
3. It worked!

Hope it helps!

**Comment by drussellmrichie** [comment]
Oh, I see! I might be able to reproduce that, then. Thanks for the tip!

**Comment by IIKshitiz26II** [comment]
Hey @chaitjo, Did you get the error "Cannot import name Word2VecVocab"? How did you fix it?
